---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  solo_rb:
    ssl_verify_mode: :verify_peer
  attributes:
    tz: 'America/Los_Angeles'
    authorization:
      sudo:
        users: [vagrant]
        passwordless: true

platforms:
  - name: ubuntu-12.04

suites:
  - name: default
    driver:
      network:
        - ["private_network", {ip: "10.10.10.200"}]
    run_list:
      - recipe[server-solo::default]
