#<% require 'kitchen-sync' %>
---
driver:
  name: vagrant
  require_chef_omnibus: 12.3.0
  customize:
    memory: 1024
    cpus: 2

provisioner:
  name: chef_solo
  chef_omnibus_install_options: -d /tmp/vagrant-cache/vagrant_omnibus
  attributes:
    tz: 'America/Los_Angeles'
    authorization:
      sudo:
        users: [vagrant]
        passwordless: true

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    driver:
      network:
        - ["private_network", {ip: "10.10.10.200"}]
    run_list:
      - recipe[chef-server-solo::default]
