AllCops:
  Include:
    - Berksfile
    - Gemfile
    - Guardfile
    - Rakefile
    - Thorfile

# This must be disabled for compatibility with knife-cookbook-doc.
Style/LeadingCommentSpace:
  Enabled: false

Metrics/LineLength:
  Max: 95

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%q': '{}'
    '%Q': '{}'

Style/RegexpLiteral:
  Exclude:
    - Guardfile

Style/SingleSpaceBeforeFirstArg:
  Exclude:
    - metadata.rb

Style/SpaceInsideHashLiteralBraces:
  Enabled: false

Style/TrailingComma:
  Exclude:
    - metadata.rb
