name             'chef-server-solo'
maintainer       'OurTownRentals.com'
maintainer_email 'evan@ourtownrentals.com'
license          'Apache 2.0'
description      'Installs and configures Chef Server.'
version          '0.4.0'

supports 'Ubuntu', '14.04'

recipe 'chef-server-solo::default', 'Installs and configures Chef Server.'

depends 'apt', '~> 2.7.0'
depends 'annoyances', '~> 1.0.0'
depends 'chef-server', '~> 3.1.1'
depends 'chef-solo-search', '~> 0.5.1'
depends 'firewall', '~> 1.1.0'
depends 'logrotate', '~> 1.9.1'
depends 'ntp', '~> 1.8.2'
depends 'openssh', '~> 1.4.0'
depends 'sudo', '~> 2.7.1'
depends 'timezone-ii', '~> 0.2.0'
depends 'users', '~> 1.8.2'
